name: fullstack-ecommerce-project

services:
  fullstack-ecommerce-pg:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fs-ecommerce-pg
